const char cert_pem[] = "-----BEGIN CERTIFICATE-----\n\
MIIB/TCCAaegAwIBAgIUA/zgMklhQQC4/ZyyHmI6DAI7FsEwDQYJKoZIhvcNAQEL\n\
BQAwUzELMAkGA1UEBhMCUk8xEjAQBgNVBAgMCUJ1Y2hhcmVzdDESMBAGA1UEBwwJ\n\
QnVjaGFyZXN0MQwwCgYDVQQKDANVUEIxDjAMBgNVBAsMBXByaW90MB4XDTI0MTIy\n\
NzE2MDMyN1oXDTM0MTIyNTE2MDMyN1owUzELMAkGA1UEBhMCUk8xEjAQBgNVBAgM\n\
CUJ1Y2hhcmVzdDESMBAGA1UEBwwJQnVjaGFyZXN0MQwwCgYDVQQKDANVUEIxDjAM\n\
BgNVBAsMBXByaW90MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJ16Y9iH/xUqjyj4\n\
SPvVRWqUOwwCCQ7KdUySc//FFNNWL4Pm29ow4znDBjY4qhKlKyQXEuHhNYjjlwc9\n\
IcSetGkCAwEAAaNTMFEwHQYDVR0OBBYEFPjRw/xRQfSwIdO4HTGpGGEAcN/bMB8G\n\
A1UdIwQYMBaAFPjRw/xRQfSwIdO4HTGpGGEAcN/bMA8GA1UdEwEB/wQFMAMBAf8w\n\
DQYJKoZIhvcNAQELBQADQQB1ea/84QfWZLWquF8+PkiZpTtcLyQ/obB1ViB9+1gP\n\
lhNq6+yxwvIngB+SZUdBx8hZ8ncP8iYlN0K2nD4queEco\n\
-----END CERTIFICATE-----\n";

unsigned int cert_pem_len = strlen(cert_pem) + 1;
